# Generated by Django 3.2.5 on 2022-01-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0002_banners_enquiry_faq_gallery_galleryimage_notifuserstatus_notify_package_page_plandiscount_progress_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='Subscriber/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Trainee',
        ),
    ]
