# Generated by Django 4.0 on 2021-12-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Yoga Trainer', 'Yoga Trainer'), ('Gym Master', 'Gym Master'), ('Nutritionist', 'Nutritionist')], max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='')),
            ],
        ),
    ]
