# Generated by Django 4.0 on 2022-01-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gym', '0002_assignsubscriber_banners_enquiry_faq_gallery_galleryimage_notiftrainerstatus_notifuserstatus_notify_'),
    ]

    operations = [
        
    ]
