# Generated by Django 3.2.9 on 2022-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_banners_enquiry_faq_gallery_galleryimage_notifuserstatus_notify_package_page_plandiscount_progress_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='Salary',
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
