<<<<<<< HEAD
# Generated by Django 4.0 on 2022-01-05 13:32

=======
# Generated by Django 3.2.5 on 2022-01-05 09:54

from django.conf import settings
>>>>>>> origin/nurtaj
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/nurtaj
        ('gym', '0002_assignsubscriber_banners_enquiry_faq_gallery_galleryimage_notiftrainerstatus_notifuserstatus_notify_'),
    ]

    operations = [
<<<<<<< HEAD
        
=======
        migrations.CreateModel(
            name='TrainerMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.trainer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Messages For Trainer',
            },
        ),
>>>>>>> origin/nurtaj
    ]
