# Generated by Django 3.2.5 on 2021-12-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
        ),
    ]
