# Generated by Django 3.2.9 on 2022-01-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0002_banners_enquiry_faq_gallery_galleryimage_notifuserstatus_notify_package_page_plandiscount_progress_s'),
    ]

    
