# Generated by Django 3.2.5 on 2022-01-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_assignsubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
