# Generated by Django 3.2.5 on 2021-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
        ),
    ]
