# Generated by Django 3.2.9 on 2022-01-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_assignsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
