# Generated by Django 4.0 on 2021-12-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_rename_name_trainee_name_of_trainee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='name_of_trainee',
            new_name='trainee',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='name_of_trainer',
            new_name='trainer',
        ),
    ]
