# Generated by Django 4.0 on 2021-12-22 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_enrolment', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], max_length=200, null=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.package')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainee')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainer')),
            ],
        ),
    ]
