# Generated by Django 4.0 on 2022-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_trainermsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
