# Generated by Django 4.0 on 2022-01-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_trainermsg_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
