# Generated by Django 4.0 on 2021-12-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='category',
            new_name='type',
        ),
    ]
