# Generated by Django 4.0 on 2021-12-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_rename_category_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='date_of_enrolment',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='status',
        ),
    ]
