# Generated by Django 4.0 on 2022-01-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_trainermsg_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermsg',
            name='user_type',
        ),
    ]
