# Generated by Django 4.0 on 2021-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_remove_package_date_of_enrolment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='date_of_enrolment',
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
