# Generated by Django 4.0 on 2021-12-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_remove_progress_date_of_enrolment_progress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
