# Generated by Django 3.2.9 on 2021-12-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_notifuserstatus'),
        ('gym', '0012_alter_progress_status'),
    ]

    operations = [
    ]
