# Generated by Django 3.2.9 on 2021-12-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_merge_0004_notifuserstatus_0012_alter_progress_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField()),
                ('ans', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='banners',
            name='alt_text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='img',
            field=models.ImageField(null=True, upload_to='banners/'),
        ),
    ]
