# Generated by Django 3.2.5 on 2021-12-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gallery'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='img',
            field=models.ImageField(null=True, upload_to='gallery_imgs/'),
        ),
    ]
