# Generated by Django 3.2.9 on 2022-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_auto_20211231_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='trainer',
            name='img',
            field=models.ImageField(null=True, upload_to='trainers/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
