# Generated by Django 3.2.5 on 2022-01-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_auto_20211231_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='max_member',
            field=models.IntegerField(null=True),
        ),
    ]
